export default [
  {
    key: 1,
    titleKey: "categories.list.menClothing",
    src: "/category.png",
    href: "/categories/men-clothing",
  },
  {
    key: 2,
    titleKey: "categories.list.mobilesAndGadgets",
    src: "/category.png",
    href: "/categories/mobiles-and-gadgets",
  },
  {
    key: 3,
    titleKey: "categories.list.consumerElectronics",
    src: "/category.png",
    href: "/categories/consumer-electronics",
  },
  {
    key: 4,
    titleKey: "categories.list.computerAndAccessories",
    src: "/category.png",
    href: "/categories/computer-and-accessories",
  },
  {
    key: 5,
    titleKey: "categories.list.cameras",
    src: "/category.png",
    href: "/categories/cameras",
  },
  {
    key: 6,
    titleKey: "categories.list.watches",
    src: "/category.png",
    href: "/categories/watches",
  },
  {
    key: 7,
    titleKey: "categories.list.menShoes",
    src: "/category.png",
    href: "/categories/men-shoes",
  },
  {
    key: 8,
    titleKey: "categories.list.homeAppliances",
    src: "/category.png",
    href: "/categories/home-appliances",
  },
  {
    key: 9,
    titleKey: "categories.list.sportsAndOutdoors",
    src: "/category.png",
    href: "/categories/sports-and-outdoors",
  },
  {
    key: 10,
    titleKey: "categories.list.automotive",
    src: "/category.png",
    href: "/categories/automotive",
  },
  {
    key: 11,
    titleKey: "categories.list.womenClothing",
    src: "/category.png",
    href: "/categories/women-clothing",
  },
  {
    key: 12,
    titleKey: "categories.list.momAndBaby",
    src: "/category.png",
    href: "/categories/mom-and-baby",
  },
  {
    key: 13,
    titleKey: "categories.list.homeAndLiving",
    src: "/category.png",
    href: "/categories/home-and-living",
  },
  {
    key: 14,
    titleKey: "categories.list.beauty",
    src: "/category.png",
    href: "/categories/beauty",
  },
  {
    key: 15,
    titleKey: "categories.list.health",
    src: "/category.png",
    href: "/categories/health",
  },
  {
    key: 16,
    titleKey: "categories.list.womenShoes",
    src: "/category.png",
    href: "/categories/women-shoes",
  },
  {
    key: 17,
    titleKey: "categories.list.womenBags",
    src: "/category.png",
    href: "/categories/women-bags",
  },
  {
    key: 18,
    titleKey: "categories.list.fashionAccessories",
    src: "/category.png",
    href: "/categories/fashion-accessories",
  },
  {
    key: 19,
    titleKey: "categories.list.grocery",
    src: "/category.png",
    href: "/categories/grocery",
  },
  {
    key: 20,
    titleKey: "categories.list.books",
    src: "/category.png",
    href: "/categories/books",
  },
];
