export default [
  {
    key: 1,
    titleKey: "categories.list.menClothing",
    src: "/category.png",
    href: "/men-clothing",
  },
  {
    key: 2,
    titleKey: "categories.list.mobilesAndGadgets",
    src: "/category.png",
    href: "/mobiles-and-gadgets",
  },
  {
    key: 3,
    titleKey: "categories.list.consumerElectronics",
    src: "/category.png",
    href: "/consumer-electronics",
  },
  {
    key: 4,
    titleKey: "categories.list.computerAndAccessories",
    src: "/category.png",
    href: "/computer-and-accessories",
  },
  {
    key: 5,
    titleKey: "categories.list.cameras",
    src: "/category.png",
    href: "/cameras",
  },
  {
    key: 6,
    titleKey: "categories.list.watches",
    src: "/category.png",
    href: "/watches",
  },
  {
    key: 7,
    titleKey: "categories.list.menShoes",
    src: "/category.png",
    href: "/men-shoes",
  },
  {
    key: 8,
    titleKey: "categories.list.homeAppliances",
    src: "/category.png",
    href: "/home-appliances",
  },
  {
    key: 9,
    titleKey: "categories.list.sportsAndOutdoors",
    src: "/category.png",
    href: "/sports-and-outdoors",
  },
  {
    key: 10,
    titleKey: "categories.list.automotive",
    src: "/category.png",
    href: "/automotive",
  },
  {
    key: 11,
    titleKey: "categories.list.womenClothing",
    src: "/category.png",
    href: "/women-clothing",
  },
  {
    key: 12,
    titleKey: "categories.list.momAndBaby",
    src: "/category.png",
    href: "/mom-and-baby",
  },
  {
    key: 13,
    titleKey: "categories.list.homeAndLiving",
    src: "/category.png",
    href: "/home-and-living",
  },
  {
    key: 14,
    titleKey: "categories.list.beauty",
    src: "/category.png",
    href: "/beauty",
  },
  {
    key: 15,
    titleKey: "categories.list.health",
    src: "/category.png",
    href: "/health",
  },
  {
    key: 16,
    titleKey: "categories.list.womenShoes",
    src: "/category.png",
    href: "/women-shoes",
  },
  {
    key: 17,
    titleKey: "categories.list.womenBags",
    src: "/category.png",
    href: "/women-bags",
  },
  {
    key: 18,
    titleKey: "categories.list.fashionAccessories",
    src: "/category.png",
    href: "/fashion-accessories",
  },
  {
    key: 19,
    titleKey: "categories.list.grocery",
    src: "/category.png",
    href: "/grocery",
  },
  {
    key: 20,
    titleKey: "categories.list.books",
    src: "/category.png",
    href: "/books",
  },
];
