name: Continuous Deploy

on:
  push:
    branches:
      - develop

jobs:
  docker-hub:
    name: Push to Docker Hub
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.CI_TOKEN }}

  # ssh-to-server:
  #   name: SSH to Server
  #   needs: docker-hub
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: SSH to Server
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           cd index
  #           sudo docker system prune -f -a
  #           sudo docker-compose stop
  #           sudo docker-compose rm -f
  #           sudo docker-compose pull
  #           sudo docker-compose up -d

  #     - name: Send message to Telegram
  #       uses: appleboy/telegram-action@master
  #       with:
  #         to: ${{ secrets.TELEGRAM_TO }}
  #         token: ${{ secrets.TELEGRAM_TOKEN }}
  #         message: |
  #           New version at: https://dev.hainmart.site
